-- Total Applicants
SELECT COUNT(*) AS TOTAL_APPLICANTS
FROM LOAN_CASE;



-- Approval Rate
SELECT
  ROUND(SUM(CASE WHEN LOAN_STATUS = 'Y' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS APPROVAL_RATE_PERCENT
FROM LOAN_STATUS;



-- Most Common Loan Term
SELECT LOAN_AMOUNT_TERM, COUNT(*) AS TERM_COUNT
FROM LOAN_CASE
GROUP BY LOAN_AMOUNT_TERM
ORDER BY TERM_COUNT DESC
FETCH FIRST 1 ROWS ONLY;



-- Median Loan Amount
SELECT MEDIAN(LOANAMOUNT) AS MEDIAN_LOAN_AMOUNT
FROM LOAN_CASE;



-- Graduate Applicants Count
SELECT COUNT(*) AS GRADUATE_APPLICANTS
FROM LOAN_CASE
WHERE EDUCATION = 'Graduate';



-- Approval by Gender
SELECT GENDER, 
       ROUND(SUM(CASE WHEN LOAN_STATUS = 'Y' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS APPROVAL_RATE
FROM LOAN_STATUS
GROUP BY GENDER;




-- Average Income
SELECT ROUND(AVG(APPLICANTINCOME), 2) AS AVERAGE_APPLICANT_INCOME
FROM LOAN_CASE;










